# @package _global_

defaults:
  - _self_
  - model: minerals.yaml
  - paths: default.yaml
  - hydra: default.yaml

root: ${hydra:runtime.cwd}

task_name: convert
weights_path: ${root}/logs/train/multiruns/2022-09-23_14-23-34/3/checkpoints/epoch_014.ckpt
convert_to: pytorch
save_path: ${root}/weights/resnet18
