# @package _global_

defaults:
  - _self_
  - datamodule: minerals.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: minerals.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
root: ${hydra:runtime.cwd}
ckpt_path: ${root}/logs/train/multiruns/2022-09-23_14-23-34/3/checkpoints/epoch_014.ckpt
