# @package _global_

defaults:
  - _self_
  - model: minerals.yaml
  - paths: default.yaml
  - hydra: default.yaml

task_name: "inference"

# directory
root: ${hydra:runtime.cwd}
output_dir: ${hydra:run.dir}

# show and save result
save_result: True

weights_path: ${root}/weights/resnet18.pt

# source directory
source_dir: ${root}/data/test

# device to inference
device: "cpu"
